name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Use just the version number

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt --verbose  # Add verbose for better logging
          pip install pytest --verbose  # Add verbose for better logging

      - name: Run Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # You can add verbosity to pytest if needed

      - name: Deploy to Production (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Production..."
          # Add actual deployment commands here
